### ISSUE TITLE
Recording feature bugs

### ISSUE THREAD

**Issue by rkantos** [AD-Vega/qarv#11]
I'm trying out qarv with a Basler acA1920-155uc and experiencing the following issues when recording:

All of these issues have been noticed with a AOI of 1920x200.

First when rotating the image from the transform menu and recording, the result looks something like when the x y axis are incorrectly rotated, or the other axis is rotated twice, as a result the image looks scrambled.

Second, when recording with the AOI=1920x200, the recorded image starts rolling over on itself like this:
![Image of Yaktocat](https://i.imgur.com/17zSXC1.png)

It seems to do this periodically at a set interval of a few hundred ms. By recording 10s @ 500fps (actual closer to <100fps (probably because of hardware limitations), the image rolls over about 20% of the height of the recorded AOI.

In both cases the picture in the preview in qarv looks like it should according to the settings.

**Comment by exzombie** [comment]
We noticed this "rolling" occasionally, but were never able to reproduce it on purpose, which made it hard to track down. Especially because it only happens on the recording path, the live image is always fine. You seem to be saying it happens more often with a smaller AOI; if I could reproduce that, it would help a lot towards finding the cause. It'll take some time because I don't have a camera at the moment. In the meantime, can you please try recording undecoded video? Somewhere in the back of my mind is an unverified claim that I have only seen glitches with 16-bit decoded videos, but never 12-bit packed (undecoded) or bayer formats.

**Comment by rkantos** [comment]
I'll come back with a recorded Bayer RG 8 and 12, which the camera is capable of. (my use doesn't require bit depth, but all the speed possible)

**Comment by rkantos** [comment]
I ran more tests with Ubuntu 18.04, and was able to reproduce the problem with similar AOI. I’m not sure what I am doing differently, but now it seems to roll over less per “rotation” Maybe it has something to do with past version of some dependency of QArv that exists on 16.04. I will try to test on that too. 
![image](https://user-images.githubusercontent.com/16664350/46056809-15662300-c15b-11e8-8609-003842ccaf78.png)

![image](https://user-images.githubusercontent.com/16664350/46056814-1eef8b00-c15b-11e8-9dfe-ba0f6cb24c0d.png)



Also either QArv Video Player needs some work, or something definitely is not right when trying to rotate the image.. I get this:

Without rotation:
![image](https://user-images.githubusercontent.com/16664350/46056560-e00d0580-c159-11e8-97e0-afc17984915c.png)
With raw (nothing happens):
![image](https://user-images.githubusercontent.com/16664350/46056637-41cd6f80-c15a-11e8-841d-249bc1f7dcb2.png)

With 90 degrees and 8-bit raw decoded:
![image](https://user-images.githubusercontent.com/16664350/46056672-6a556980-c15a-11e8-9840-782c29755292.png)
It seems to be rolling over too:
![image](https://user-images.githubusercontent.com/16664350/46056722-b3a5b900-c15a-11e8-86b8-89f405d3fa5d.png)


with huffyuv:
![image](https://user-images.githubusercontent.com/16664350/46056574-f74bf300-c159-11e8-9bce-dfb33c077d74.png)

The only video format that functions with rotation is the “TIFF images”.

**Comment by exzombie** [comment]
We've finally had some time to deal with this. Please test and thanks again for a detailed report :)
