### ISSUE TITLE
qarv and qarv_player framerate limitations 999fps & 99fps

### ISSUE THREAD

**Issue by rkantos** [AD-Vega/qarv#12]
As before, I am using a Basler acA1920-155uc camera, which by design is able to record 1920x1200 @ 155fps. By reducing the AOI, the camera can go up to thousands of fps. Currently it seems qarv can go to 999fps and qrv_player can play up to 99fps. I don't see a reason for these limitations, since most manufacturer SDK players don't have them either.

**Comment by exzombie** [comment]
First, thanks for reporting this and other issues :) 

The limitation comes purely from the GUI, in particular the size of the FPS box. There is no reason to not make it larger, so I will.

**Comment by rkantos** [comment]
> First, thanks for reporting this and other issues :)
> 
> The limitation comes purely from the GUI, in particular the size of the FPS box. There is no reason to not make it larger, so I will.

I recommend making it unlimited or max of 1 million fps, since that is the limit in Basler Pylon Viewer on Windows.

**Comment by exzombie** [comment]
Fixed in 1d9ec7ebec1ffeeb88accf6e00d01194d35c1d3a. Sorry for taking so long for such a trivial thing.
