### ISSUE TITLE
Failed to build master qarv

### ISSUE THREAD

**Issue by EmmanuelP** [AD-Vega/qarv#2]
Hi,

I've tried to build qarv, but compilation failed:

PKG_CONFIG_PATH=/home/pacaud/Sources/INSTALL-aravis/lib/pkgconfig/ cmake .
-- The C compiler identification is GNU 6.2.1
-- The CXX compiler identification is GNU 6.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Program version not specified, using git description.
QArv version: '1241f23'
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/bin/qmake-qt4 (found version "4.8.7") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Checking for one of the modules 'aravis-0.4;aravis-0.2'
-- Checking for module 'gio-2.0'
--   Found gio-2.0, version 2.48.2
-- Checking for module 'libswscale'
--   Found libswscale, version 4.0.100
-- Checking for module 'libavcodec'
--   Found libavcodec, version 57.24.102
-- Checking for module 'libavutil'
--   Found libavutil, version 55.17.103
-- Looking for av_pix_fmt_desc_get
-- Looking for av_pix_fmt_desc_get - found
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pacaud/Sources/qarv
[pacaud@lappc-p620 qarv (master %)]$ LANG=C make
[  1%] Generating qarv_sl.qm
Updating '/home/pacaud/Sources/qarv/qarv_sl.qm'...
    Generated 189 translation(s) (189 finished and 0 unfinished)
[  2%] Generating src/filters/moc_levels.cxx
[  3%] Generating ui_levels.h
[  4%] Generating src/recorders/moc_rawrecorders.cxx
[  6%] Generating src/recorders/moc_gstrecorders.cxx
[  7%] Generating src/recorders/moc_imagerecorder.cxx
[  8%] Generating src/decoders/moc_mono12packed.cxx
[  9%] Generating src/decoders/moc_monounpackeddecoders.cxx
[ 10%] Generating src/decoders/moc_bayer.cxx
[ 12%] Generating src/moc_glvideowidget.cxx
[ 13%] Generating src/moc_glhistogramwidget.cxx
[ 14%] Generating src/moc_qarvmainwindow.cxx
[ 15%] Generating src/moc_roicombobox.cxx
[ 17%] Generating src/moc_globals.cxx
[ 18%] Generating src/moc_workthread.cxx
[ 19%] Generating src/api/moc_qarvtype.cxx
[ 20%] Generating src/api/moc_qarvgui.cxx
[ 21%] Generating src/api/moc_qarvcamera.cxx
[ 23%] Generating src/api/moc_qarvcameradelegate.cxx
[ 24%] Generating src/filters/moc_filter.cxx
[ 25%] Generating ui_mainwindow.h
[ 26%] Generating qrc_icons.cxx
Scanning dependencies of target qarv-2
[ 28%] Building CXX object CMakeFiles/qarv-2.dir/src/filters/moc_levels.cxx.o
[ 29%] Building CXX object CMakeFiles/qarv-2.dir/src/filters/levels.cpp.o
[ 30%] Building CXX object CMakeFiles/qarv-2.dir/src/recorders/moc_rawrecorders.cxx.o
In file included from /home/pacaud/Sources/qarv/src/recorders/recorder.h:23:0,
                 from /home/pacaud/Sources/qarv/src/recorders/rawrecorders.h:23,
                 from /home/pacaud/Sources/qarv/src/recorders/moc_rawrecorders.cxx:9:
/home/pacaud/Sources/qarv/src/api/qarvdecoder.h:101:47: error: use of enum 'PixelFormat' without previous declaration
   static QArvDecoder\* makeSwScaleDecoder(enum PixelFormat fmt,
                                               ^~~~~~~~~~~
CMakeFiles/qarv-2.dir/build.make:219: recipe for target 'CMakeFiles/qarv-2.dir/src/recorders/moc_rawrecorders.cxx.o' failed
make[2]: **\* [CMakeFiles/qarv-2.dir/src/recorders/moc_rawrecorders.cxx.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/qarv-2.dir/all' failed
make[1]: **\* [CMakeFiles/qarv-2.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by exzombie** [comment]
This looks eerily familiar ;) . I'll look into it this weekend.

**Comment by exzombie** [comment]
It seems you were building the master branch, not the `edouard` branch. The master branch didn't yet have the update for the latest ffmpeg. This is now fixed there as well, and builds for me with ffmpeg-3.1.3.
