### ISSUE TITLE
Issue adding second GenICam camera

### ISSUE THREAD

**Issue by robotaiguy** [AD-Vega/qarv#20]
I have everything working exactly as I would like. But when I add a second Teledyne Dalsa Genie Nano C4030 to my network (each camera is plugged into its own 1 GigE NIC), it will successfully recognize that there are 3 cameras (1 Fake, 2 Nano's). But when it loops through to assign the model and vendor, it fills in "" for the model and vendor on the new camera. Although, the camid will show the entire name, including the serial number (which is the only difference between the cameras...same firmware, same vendor, same model...but different serial number). But it errors out when checking if it is a camera.
If I use either camera alone, it's fine. If I reverse which nics they are plugged into, but only add 1 of them at a time, it works fine. It just seems to have an issue with both of them connected at the same time. I am currently stepping through the program to see if I can figure out what's going on. 
Any ideas?

**Comment by robotaiguy** [comment]
It seems to break inside of the arv_gv_device_load_genicam function when it attempts to read the xml file for whichever camera is the most recently connected device to my computer. If I switch the connection order, it moves the problem to that camera. For one camera, the xml file is read and it runs through the feature-values. For the second camera, xml file is null.

**Comment by robotaiguy** [comment]
It appears that this issue is NOT caused by this application, nor the Aravis framework. I ran a test with the Dalsa GigeV framework network status monitor, and the problem persists. So it seems there is some conflict between NIC's that I need to resolve. Closing this issue, please forgive.

**Comment by exzombie** [comment]
Thanks for the followup. Good luck with the diagnosis!
