### ISSUE TITLE
Aravis 0.8.0-1 fix

### ISSUE THREAD

**Issue by Szamtu** [AD-Vega/qarv#21]
Hello,
Thank you a lot for the great app.

I suggest you a small fix, in order to allow build it with the newest aravis from repo  `aravis 0.8.0-1`

https://github.com/AD-Vega/qarv/blob/8fbb6dd61e81193329737a323280c9550cbfde50/src/qarvfeaturetree.cpp#L140

and:

https://github.com/AD-Vega/qarv/blob/8fbb6dd61e81193329737a323280c9550cbfde50/src/api/qarvcamera.cpp#L835

`arv_gc_float_get_unit` has changed and now it uses only `ArvGcFloat` pointer.

**Comment by exzombie** [comment]
Ah, so aravis 0.8 was released at last :smiley: . Thanks for the notification! As you may have noticed, we already have most of the API changes in place, now we can finish it.
