### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by multiflexi** [AD-Vega/qarv#4]
Hi,
when building QArv with the Aravis from master branch I get this error:

[qarv_build.log](https://github.com/AD-Vega/qarv/files/2057706/qarv_build.log)

I am using Ubuntu 18.04

**Comment by EmmanuelP** [comment]
It is an issue in aravis. Fixed in master https://github.com/AravisProject/aravis/commit/e1eeb716480ad891fe926cf06ece92ae1b3db54e
